### PR TITLE
Using PORT as env in workbench app

### PR DESCRIPTION
**Pull request by tommasodotNET**
This PR addresses #167 

Update server configuration to use 'localhost' as the host and dynamically assign the port number

### CODE REVIEW

**Review by bkrabach — CHANGES_REQUESTED** [review]
We have app registrations and other configurations dependent upon the explicit use of 127.0.0.1 along with the specific port and https requirement.  We will need to investigate the impact of the host change in the places we're using it.

As alternative or compromise until we investigate further, perhaps we apply the same approach you have provided for port and allow the host to be configured via env var, with the default remaining at 127.0.0.1?

**Comment by tommasodotNET** [comment]
Using localhost won't break the app registration. I've tested and the login still works fine...

**Comment by bkrabach** [comment]
> Using localhost won't break the app registration. I've tested and the login still works fine...

Appreciate the testing and verification of that!  Have you tried it with Codespaces as well?  This is the primary path we've suggested for folks who want to get a quick dev environment to try it out and hack on their own assistants.

We have a hosted version that we use for our team and others that has a different app registration with some customizations that we cannot modify under current Azure portal changes and some other places where we're explicit about using https://127.0.0.1:4000 that is some work to change, beyond what is visible in the repo.  Those are the things I need to check on before committing a change to the default behavior.

**Review by bkrabach — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
